### ISSUE TITLE
Broken planner?

### ISSUE THREAD

**Issue by Mutachre** [3cpm/desktop#111]
Bug in planner or planner broken. Not showing data correctly:

<img width="1368" alt="Schermata 2022-02-08 alle 10 55 01" src="https://user-images.githubusercontent.com/62408551/152963725-f78d0d67-089e-43f0-a096-292b0069386c.png">

**Desktop app:**
 - MacOSX (12.1)
 - Apple chip M1
 - 3C latest v.

**Comment by coltoneshaw** [comment]
@Mutachre - Can you do menu > Help > Reset profile and resync the data over? You also might only have one column selected on that dropdown.
