### ISSUE TITLE
Not all bots listed

### ISSUE THREAD

**Issue by mfread** [3cpm/desktop#113]
**Describe the bug**
I have 18 bots running (all enabled, all long, mixed currency pairs) yet only 15 are listed in the 3CPM interface.

**To Reproduce**
Bots running     Listed in 3CPM
FTM/AUD          Y
SHIB\AUD          Y
ATOM/USDT      N
AVAX/AUD         Y
AMP/USDT        N
MATIC/AUD         Y
DOT/AUD         Y
ETH/AUD         Y
LUNA/AUD         Y
AXS/AUD         Y
GALA/AUD         Y
BNB/AUD         Y
BTC/AUD         Y
DOGE/AUD         Y
TRX/USDT        N
ADA/AUD         Y
SOL/AUS         Y
XRP/AUD         Y

**Expected behavior**
All bots should be listed

**Screenshots**
Not really applicable

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge Version 98.0.1108.43 (Official build) (64-bit)
 - Version: 3CPM (3c-portfolio-manager-2.0.0-win-x64.exe)  ** this isn't shown anywhere in the actual 3CPM app; should be under Help->About
 
**Additional context**
New installation. 
Just 1 profile configured.

**Comment by coltoneshaw** [comment]
@mfread - What currencies do you have selected in the Settings? Right now it looks like USDT may not be seleted. Due to conversion errors, You cannot select both at once. so, I suggest making a seperate USDT profile. That is a future request to have both possible at the same time.

**Comment by coltoneshaw** [comment]
Closing this for now. #57 will track this moving forward. Looking to get it in the next release.

**Comment by mfread** [comment]
Thank you. Yes, I didn't realize I needed to create multiple profiles, one per base currency. Doing so has resolved my issue :)
