### ISSUE TITLE
Feature - Sell at Market

### ISSUE THREAD

**Issue by mfread** [3cpm/desktop#114]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like to see a new column that shows 'at market profit' - which is a calculation that illustrates how much of a profit (or loss) I'd make if I sold this asset right now. Be nice to also have a little icon that when clicked placed a sell order with my exchange. Yes, I understand there's price movement and slippage involved etc, but this value would give me an indication of what I might get should I sell right now.

**Describe alternatives you've considered**
A manual calculation but it's a moving target - that's why we have automation to do the heavy lifting for us :)

**Additional context**
If I see price action going up a little then this would give me a signal to click on the 'sell now' icon. Handy if I'm slightly in profit in a badly bearish market, or I just want to get out and take my losses because price action is (I think) telling me the bearish trend will continue and I can't/don't want to fund any more Safety LEvels.

**Comment by coltoneshaw** [comment]
Hey @mfread - Wouldn't that be the current profit column that shows how up/down you are?

**Comment by mfread** [comment]
Thank you. Yes, that column does the trick. Also the 'Unrealised Profit' box at the top provides a handy total for the column. I'm slowly getting used to the interface - without any documentation showing me how to interpret certain sections I was at a bit of a loss. 

Incidentally, the ROI box at the top right - when I hover over it gives me a total account figure (USDT presumably as that's my profile's base currency?) but when I look at Binance it shows a different number (which can only be viewed with fiat currency - mine's set to USD). Would that explain a $500 difference on a $12,110 balance reported by 3CPM?
