### ISSUE TITLE
 Error updating your data. Check the console for more information.

### ISSUE THREAD

**Issue by gabrielcr78** [3cpm/desktop#125]
**Describe the bug**

**To Reproduce**
1. try to synchronize the account by clicking on any of the Sync buttons.
2. see the error popup saying: "Error updating your data. Check the console for more information."
3. 3. tried also re-adding the account... no luck

![Captura de pantalla 2022-04-20 101919](https://user-images.githubusercontent.com/7981530/164277390-6a0ecadf-6703-4eb1-be03-d5ae382de802.jpg)

**Expected behavior**
normally it just fetch your updated information from 3C

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Widows 11
 - Browser: Chrome
 - Version [e.g. 22]: Version 100.0.4896.127 (Official Build) (64-bit)
**Additional context**
fetching Config
configSlice.ts:19 setting the config
configActions.ts:53 setting since there are no account IDs!
3Commas.ts:32 Object
preload.ts:14 Updating 3Commas data.
Actions.ts:228 Error: Error invoking remote method 'api-updateData': SqliteError: table deals has no column named last_known_position_info
syncNewProfileData @ Actions.ts:228
3Commas.ts:32 Object
preload.ts:14 Updating 3Commas data.
Actions.ts:228 Error: Error invoking remote method 'api-updateData': SqliteError: table deals has no column named last_known_position_info
syncNewProfileData @ Actions.ts:228
3Commas.ts:32 {options: {…}}
preload.ts:14 Updating 3Commas data.
Actions.ts:228 Error: Error invoking remote method 'api-updateData': SqliteError: table deals has no column named last_known_position_info

**Comment by JozefJarosciak** [comment]
I have the same problem, the application stopped working. Tried to re-create the 3c keys, but it did not help. The app no longer works. This is actually concerning because the issue is not with 3c, I confirmed that the API works as expected. I very much hope that the app does not communicate with 3C through some intermediary network that is currently down.

**Comment by coltoneshaw** [comment]
Hey. Sorry 3C added a profile field that's not in the database currently. 

It should be open up the console with menu > view > dev tools then console.

If you scroll up you should see profileID =“” in one of the queries. If you copy that ID string and do 

```

await window.ThreeCPM.Repository.Database.run(“thatpProfileID”, “ALTER TABLE deals ADD last_known_position_info text;”)

```

I'm actually away right now with only mobile, great time to have it break.

**Comment by doharvey** [comment]
Thank you for your response.  

I have try to alter table in sqlite3 instead and it worked. ;)
Here is what i did:

```
[dharvey@dominic-box databases]$ pwd
/home/dharvey/.config/3C Portfolio Manager/databases

[dharvey@dominic-box databases]$ sqlite3 3cdd68f7-d76d-417c-b06c-ae9df7aa1bf0.sqlite3 
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> ALTER TABLE deals ADD last_known_position_info text;
sqlite> .exit
[dharvey@dominic-box databases]$ 
```

**Comment by doharvey** [comment]
Sorry, i am a Linux user so i  run these command in the shell.  

sqllite also exist for Windows but i am not a Windows expert...  sorry

**Comment by gabrielcr78** [comment]
> Hey. Sorry 3C added a profile field that's not in the database currently.
> 
> It should be open up the console with menu > view > dev tools then console.
> 
> If you scroll up you should see profileID =“” in one of the queries. If you copy that ID string and do
> 
> ```
> 
> await window.ThreeCPM.Repository.Database.run(“thatpProfileID”, “ALTER TABLE deals ADD last_known_position_info text;”)
> ```
> 
> I'm actually away right now with only mobile, great time to have it break.
I opened the console but i dont see that message anywhere

**Comment by coltoneshaw** [comment]
```
await window.ThreeCPM.Repository.Database.run(await window.ThreeCPM.Repository.Config.get('all').current, “ALTER TABLE deals ADD last_known_position_info text;”)
```

This might be easiest. Yes on the app under the tool bar go to view > dev console > console

**Comment by gabrielcr78** [comment]
![image](https://user-images.githubusercontent.com/7981530/164356330-07fbfb15-141d-42bd-9619-7630eba74261.png)

**Comment by gabrielcr78** [comment]
so i started the program,, went to the console and type that inthe bottom:

![image](https://user-images.githubusercontent.com/7981530/164356410-8a9eeb49-2cde-4549-9210-a062efc1f7bb.png)

**Comment by gabrielcr78** [comment]
![image](https://user-images.githubusercontent.com/7981530/164356667-bcfb1aa2-ea04-458b-854e-53b58242942a.png)

**Comment by coltoneshaw** [comment]
Can you swap out the " to in that string? It looks like maybe they copied weird. If not I can try to write up a quick function to fix it until I get home

**Comment by gabrielcr78** [comment]
you were rirght about the quote symbol.. changed it and now it's doing something different. 
![image](https://user-images.githubusercontent.com/7981530/164357241-c48ad3e2-40c3-4233-8c27-4565813e2d37.png)

**Comment by gabrielcr78** [comment]
oh it might be because i had erased all my data in the morning, now it wont let me add the new account

**Comment by gabrielcr78** [comment]
I can try downloading SQLLITE for widows and tr to correct the table with it.. but do you happen to know where that DB is stored?

**Comment by gabrielcr78** [comment]
well, removed the app and reinstalled and recreated the first profile.. seems like there's a DB now:

![image](https://user-images.githubusercontent.com/7981530/164364883-3773f935-7a67-4648-a1ed-8ac8eba1e82b.png)

**Comment by gabrielcr78** [comment]
HAH!!!! i was able to pull the profiles object with this:
await window.ThreeCPM.Repository.Config.get('all')
from there copied the ProfileID  and used the first command you gave us:


await window.ThreeCPM.Repository.Database.run("theProfileID", "ALTER TABLE deals ADD last_known_position_info text;")


it's working now!!

thanks a lot!!!

**Comment by mfread** [comment]
@gabrielcr78 I tried that and got "Uncaught SyntaxError: Invalid or unexpected token.
![image](https://user-images.githubusercontent.com/1237242/164374301-9276d8eb-5d46-43a2-944b-aacab8cd5b5f.png)

**Comment by Kevin24111** [comment]
Hello Guys, i have also this problem with Mac OS Monterey since yesterday.

**Comment by hamedmirza** [comment]
> HAH!!!! i was able to pull the profiles object with this: await window.ThreeCPM.Repository.Config.get('all') from there copied the ProfileID and used the first command you gave us:
> 
> await window.ThreeCPM.Repository.Database.run("theProfileID", "ALTER TABLE deals ADD last_known_position_info text;")
> 
> it's working now!!
> 
> thanks a lot!!!

Awesome job, worked for me too. thanks

**Comment by tomqw** [comment]
After You update Your API keys there is also another error:
Actions.ts:228 Error: Error invoking remote method 'api-updateData': TypeError: Cannot read property 'updated_at' of undefined

**Comment by Ryan-Steelpixel** [comment]
> ```
> await window.ThreeCPM.Repository.Database.run(await window.ThreeCPM.Repository.Config.get('all').current, “ALTER TABLE deals ADD last_known_position_info text;”)
> ```

I got same error when trying to run the two lines that gabrielcr78 said worked for him. Error shows after try save when adding in API keys after doing a Reset All Data.

**Comment by JozefJarosciak** [comment]
> await window.ThreeCPM.Repository.Database.run(<yourIdHere>, "ALTER TABLE deals ADD last_known_position_info text;")

@coltoneshaw - this worked like a charm... thank you for spelling it out for us! Much appreciated.

**Comment by mfread** [comment]
Referencing Colton's post ... https://github.com/3cpm/desktop/issues/125#issuecomment-1105172480

@coltoneshaw I've tried again and am still getting the same error as I posted here https://github.com/3cpm/desktop/issues/125#issuecomment-1104705334

I suspect it works for those on Linux but not Windows 10??

I think I'm simply going to have to wait for your update release :)

=Mark

**Comment by gabrielcr78** [comment]
it actually works for me on windows with the fix described

**Comment by bgratt** [comment]
@coltoneshaw I followed the steps above, but still without success. I am now getting the following error. Thanks in advance for all your efforts! 
<img width="553" alt="sc1" src="https://user-images.githubusercontent.com/1094340/164801753-a03fa6c1-9417-4499-9f5a-f7f8df6d0a9f.png">

**Comment by Ryan-Steelpixel** [comment]
> @coltoneshaw I followed the steps above, but still without success. I am now getting the following error. Thanks in advance for all your efforts! <img alt="sc1" width="553" src="https://user-images.githubusercontent.com/1094340/164801753-a03fa6c1-9417-4499-9f5a-f7f8df6d0a9f.png">

I too got that error msg when I tried to do the fix a 2nd time, and it makes sense as you have already inserted the missing table so can't do it again. If you want to try the steps again from start you will have to Reset All Data first.

**Comment by Ryan-Steelpixel** [comment]
> it actually works for me on windows with the fix described

Can you confirm if it worked to apply fix when you already had a previously working profile setup, or if it worked to do these steps when trying to do create profile which is where I'm stuck.

**Comment by Kevin24111** [comment]
Error: Error invoking remote method 'api-updateData': TypeError: SQLite3 can only bind numbers, strings, bigints, buffers, and null

Same problem here.

**Comment by Metaflector** [comment]
Hi... I have gone through the process but get the following error...
Uncaught SyntaxError: Invalid or unexpected token

Can you advise please...

**Comment by roadie** [comment]
I'm using MacOS, and after trying the 5 steps process in the Console, I'm also getting this error:
Error: Error invoking remote method 'api-updateData': TypeError: SQLite3 can only bind numbers, strings, bigints, buffers, and null

**Comment by jwiedeman** [comment]
> Steps posted by Mccrystal in Discord.
> 
> 1. Open 3C Portfolio Manager
> 2. In menu select "View" then "Toggle Developer Tools"
> 3. Open the tab "Console" and enter:
> 
> ```
> await window.ThreeCPM.Repository.Config.get('all')
> ```
> 
> 4. Copy the profile id including quotes
> 5. Don't forget to replace  with what you copied in step 4 and enter:
> 
> ```
> await window.ThreeCPM.Repository.Database.run(<yourIdHere>, "ALTER TABLE deals ADD last_known_position_info text;")
> ```

Worked for me!

**Comment by mfread** [comment]
The 5 steps works for some but not others (inc me). Awaiting 3CPM binary update from Colton.

**Comment by fsck66** [comment]
Paste commands into text editor first to make sure they aren’t getting
mangled (and use the copy button instead of highlighting / copy/paste) just
saying, could be related…

I also had to do it for each profile on 3CPM

**Comment by coltoneshaw** [comment]
Check out the latest release and let me know - https://github.com/3cpm/desktop/releases/tag/v2.0.2
